# Generated by Django 3.0.7 on 2020-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_color',
            field=models.CharField(default='green', max_length=64),
        ),
    ]
